[build]
target = "index.html"

[watch]
ignore = ["static/javascripts/bundle.js", ".DS_Store"]

[[proxy]]
rewrite = "/api/"
backend = "http://localhost:9000/api/"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "$TRUNK_SOURCE_DIR/build/bundle-javascript-files.sh"]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "$TRUNK_SOURCE_DIR/build/update-service-worker.sh"]
