[package]
name = "webchordr"
version = "0.1.5"
authors = ["Daniel Corn <info@cundd.net>"]
edition = "2018"

[dependencies]
log = "0.4"
web_logger = "0.2"
serde = "1"
serde_derive = "1"
stdweb = "0.4.20"
rand = "0.7.2"
libchordr = { path = "../libchordr" }
anyhow = "1.0.28"
failure = "0.1"
yew = { version="0.14.3", features = ["std_web"] }
yew-router = { version = "0.11.0", features = ["std_web"] }
percent-encoding = "2.1.0"
wee_alloc = "0.4.5"

#yew = { git = "https://github.com/yewstack/yew", branch = "master", features = ["std_web"] }
#yew-router = { git = "https://github.com/yewstack/yew_router", branch="master", features = ["std_web"] }
