[package]
name = "webchordr"
version = "0.1.0"
authors = ["Daniel Corn <info@cundd.net>"]
edition = "2018"

[dependencies]
log = "0.4"
web_logger = "0.2"
serde = "1"
serde_derive = "1"
stdweb = "0.4.20"
libchordr = { path = "../libchordr" }
failure = "0.1"
yew = {git = "https://github.com/yewstack/yew", branch = "master"}
