[package]
name = "srvchord"
version = "0.1.0"
authors = ["Daniel Corn <info@cundd.net>"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
diesel = { version = "1.3", features = ["sqlite", "r2d2"] }
diesel_migrations = "1.3"
log = "0.4"
libchordr = { path = "../libchordr" }

[dev-dependencies]
parking_lot = { version = "0.10", features = ["nightly"] }
rand = "0.7"

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
#features = ["diesel_sqlite_pool"]
features = ["tera_templates", "diesel_sqlite_pool", "serve", "json"]
