[global]
# Path to the directory of chorddown files
song_dir = "../webchordr/app/static/songs"

# Path to the static files
static_files_dir = "../webchordr/app/dist"

[release.databases.main_database]
url = "db/db.sqlite"

[staging.databases.main_database]
url = "db/stage-db.sqlite"

[debug]
#log = "debug"
port = 9000

[debug.databases.main_database]
url = "db/dev-db.sqlite"
