[global]
# Path to the directory of chorddown files
song_dir = "../webchordr/static/songs"

# Path to the static files
static_files_dir = "../webchordr/dist"

template_dir = "static"


[production.databases.main_database]
url = "db/db.sqlite"

[staging.databases.main_database]
url = "db/stage-db.sqlite"

[development]
#log = "debug"
address = "localhost"
port = 9000

[development.databases.main_database]
url = "db/dev-db.sqlite"
