[package]
name = "libchordr"
version = "0.1.0"
authors = ["Daniel Corn <info@cundd.net>"]
edition = "2018"

[lib]
name = "libchordr"
path = "src/lib.rs"

[features]
pdf = ["printpdf"]

[dependencies]
