[package]
name = "libchordr"
version = "0.1.0"
authors = ["Daniel Corn <info@cundd.net>"]
edition = "2018"

[lib]
name = "libchordr"
path = "src/lib.rs"

[features]
pdf = ["printpdf"]

[dependencies]
serde = {version ="^1.0", features = ["derive"]}
serde_derive = "^1.0"
printpdf = { version = "0.2.8", optional = true }
rand = "0.7.2"
encoding = "^0.2.33"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
serde_json = "^1.0"
