use crate::tokenizer::{Token, Directive};

#[cfg(test)]
pub fn get_test_tokens() -> Vec<Token> {
    vec![
        Token::comment("A simple ChordPro song."),
        Token::Newline,
        Token::Directive(Directive::title("Swing Low Sweet Chariot")),
        Token::Newline,
        Token::Newline,
        Token::Directive(Directive::start_of_chorus("")),
        Token::Newline,
        Token::literal("Swing "),
        Token::chord("D"),
        Token::literal("low, sweet "),
        Token::chord("G"),
        Token::literal("chari"),
        Token::chord("D"),
        Token::literal("ot,"),
        Token::Newline,
        Token::literal("Comin’ for to carry me "),
        Token::chord("A7"),
        Token::literal("home."),
        Token::Newline,
        Token::literal("Swing "),
        Token::chord("D7"),
        Token::literal("low, sweet "),
        Token::chord("G"),
        Token::literal("chari"),
        Token::chord("D"),
        Token::literal("ot,"),
        Token::Newline,
        Token::literal("Comin’ for to "),
        Token::chord("A7"),
        Token::literal("carry me "),
        Token::chord("D"),
        Token::literal("home."),
        Token::Newline,
        Token::Directive(Directive::EndOfChorus),
        Token::Newline,
        Token::Newline,
        Token::literal("I "),
        Token::chord("D"),
        Token::literal("looked over Jordan, and "),
        Token::chord("G"),
        Token::literal("what did I "),
        Token::chord("D"),
        Token::literal("see,"),
        Token::Newline,
        Token::literal("Comin’ for to carry me "),
        Token::chord("A7"),
        Token::literal("home."),
        Token::Newline,
        Token::literal("A "),
        Token::chord("D"),
        Token::literal("band of angels "),
        Token::chord("G"),
        Token::literal("comin’ after "),
        Token::chord("D"),
        Token::literal("me,"),
        Token::Newline,
        Token::literal("Comin’ for to "),
        Token::chord("A7"),
        Token::literal("carry me "),
        Token::chord("D"),
        Token::literal("home."),
        Token::Newline,
        Token::Newline,
        Token::Directive(Directive::comment("Chorus")),
        Token::Newline,
    ]
}
