[package]
name = "chordr"
version = "0.1.0"
authors = ["Daniel Corn <info@cundd.net>"]
edition = "2018"

[[bin]]
name = "chordr"
path = "src/bin.rs"

[dependencies]
libchordr = { path = "../libchordr" }
clap = "2.33.0"
