name: srvchord

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install trunk
        run: cargo install --locked trunk
      - name: Build
        run: trunk build
        working-directory: ./webchordr/app
      - name: Run tests
        run: cargo test --verbose -p srvchord
