name: synchord

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Install openssl
        run: sudo apt-get install libssl-dev
      - name: Build
        run: cargo build --verbose -p synchord
      - name: Run tests
        run: cargo test --verbose -p synchord
